PACKAGE_NAME="8189fs"
PACKAGE_VERSION="5.7.9"
BUILT_MODULE_NAME[0]="8189fs"
DEST_MODULE_LOCATION[0]="/kernel/drivers/net/wireless"
MAKE[0]="'./dkms-make.sh' ${kernelver}"
CLEAN="make clean"
PRE_BUILD="dkms-pre-build.sh ${kernelver}"
AUTOINSTALL="yes"
